### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by dieghernan** [dieghernan/RKI-Corona-Atlas#1]
The site is now live with the basic UI. Some things still pending @rodrihgh :

- [x] Write text content and titles: It should be done in [index.Rmd](https://github.com/dieghernan/RKI-Corona-Atlas/blob/master/_R/index.Rmd) and [index.Rmd](https://github.com/dieghernan/RKI-Corona-Atlas/blob/master/_R/index_en.Rmd). Use markdown style.
- [x] Show Kosovo as independent country (as it is recognized by Germany).
- [x] Review German translation of the labels in  [index.Rmd](https://github.com/dieghernan/RKI-Corona-Atlas/blob/master/_R/index.Rmd) (marked with `#RHH`) and [risk_level_code.csv](https://github.com/dieghernan/RKI-Corona-Atlas/blob/master/assets/data/risk_level_code.csv).
- [x] Review some risk levels (e.g. Mauritania shows up as no risk area, while it actually is a risk area)
- [x] Add own "dummy" risk level for Germany (since its current displayed status as "No risk area" is neither for many countries, nor for the RKI itself true).
- [x] Review new German info on [index.Rmd](https://github.com/dieghernan/RKI-Corona-Atlas/blob/master/_R/index.Rmd) after the implementation of the new scrapper.
- [x] Update [README.md](https://github.com/dieghernan/RKI-Corona-Atlas/blob/master/README.md)
- [x] Review and polish [_config.yml](https://github.com/dieghernan/RKI-Corona-Atlas/blob/master/_config.yml).
- [x] Deploy on domain and check links https://www.deadlinkchecker.com/
- [x] Google Analytics & Search Console to make Google aware we are live.
- [x] Enforce https:// on GitHub.

## Important Note

After each commit, [GitHub Actions](https://github.com/dieghernan/RKI-Corona-Atlas/actions) would automatically rebuild the pages adding an additional commit. When working with git that means that after each pushed commit you would need to pull changes (running time of the action: ~3-4 minutes)

**Comment by dieghernan** [comment]
https://github.com/dieghernan/RKI-Corona-Atlas/issues/2#issuecomment-826385308

Moving scrapper-related thread to this issue, as it is related with the initial setup

**Comment by rodrihgh** [comment]
I have added some info about the project and the developers in an About tab

@dieghernan check your part and add/delete whatever you feel like: https://github.com/dieghernan/RKI-Corona-Atlas/blob/master/_pages/about.md#diego

**Comment by dieghernan** [comment]
@rodrihgh if you are ok with the _config file we can close the issue, good job 👍🏻

**Comment by rodrihgh** [comment]
@dieghernan I am ok with it :) Good job to you too;
