### ISSUE TITLE
Corona timelapse

### ISSUE THREAD

**Issue by rodrihgh** [dieghernan/RKI-Corona-Atlas#18]
Germany has lifted the travel restrictions for all regions upon the mildness of the omicron variant.

Since this renders the site quite uninteresting, I suggest to collect all the risk levels for each country over time so that some nice visualization can be implemented. This can be broken down into two tasks:

1. The creation of a table with all the risk levels over time, assigned to @rodrihgh 
2. The (probably R-based) visualization, assigned to @dieghernan 

My plan for the table is to have it as a CSV with the following structure:

|  | COUNTRY_ISO_CODE_A | COUNTRY_ISO_CODE_B | ... |
| --- | --- | --- | --- |
| date_1 | risk_code1.A | risk_code1.B | ... |
| date_2 | risk_code2.A | risk_code2.B | ... |
| ... | ...  | ...  | ...  |

**Comment by rodrihgh** [comment]
I have created a table with dummy risk level codes in case you want to start playing around with the visualization:

https://github.com/dieghernan/RKI-Corona-Atlas/blob/dev/timelapse/mockup.csv

**Comment by dieghernan** [comment]
An initial attempt (really basic, it can be largely improved):

<details>
``` r
download.file("https://raw.githubusercontent.com/dieghernan/RKI-Corona-Atlas/dev/timelapse/mockup.csv",
              "mockup.csv")
download.file("https://raw.githubusercontent.com/dieghernan/RKI-Corona-Atlas/master/assets/geo/country_shapes.geojson",
              "country_shapes.geojson")


library(tidyverse)
library(sf)
#> Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1; sf_use_s2() is TRUE
library(gganimate)

evo <- read_csv("mockup.csv")
#> New names:
#> * `` -> ...1
#> Rows: 52 Columns: 199
#> -- Column specification --------------------------------------------------------
#> Delimiter: ","
#> dbl  (198): AFG, AGO, ALB, AND, ARE, ARG, ARM, ATG, AUS, AUT, AZE, BDI, BEL,...
#> date   (1): ...1
#> 
#> i Use `spec()` to retrieve the full column specification for this data.
#> i Specify the column types or set `show_col_types = FALSE` to quiet this message.
shape <- st_read("country_shapes.geojson")
#> Reading layer `country_shapes' from data source 
#>   `C:\Users\diego\AppData\Local\Temp\RtmpiI3gt8\reprex-4e034ac1e65-vivid-eider\country_shapes.geojson' 
#>   using driver `GeoJSON'
#> Simple feature collection with 198 features and 1 field
#> Geometry type: MULTIPOLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -180 ymin: -59.51912 xmax: 180 ymax: 83.65187
#> Geodetic CRS:  WGS 84
shape <- st_transform(shape, "+proj=robin")

# Modify evo
n <- names(evo)
n[1] <- "date"
names(evo) <- n
evo2 <- evo %>%
  pivot_longer(!date, names_to = "ISO3_CODE")


# Background
bck <- st_graticule() %>%
  st_bbox() %>%
  st_as_sfc() %>%
  st_transform(3857) %>%
  st_segmentize(500000) %>%
  st_transform(st_crs(shape))


shapeend <- shape %>% left_join(evo2) %>%
  arrange(date, ISO3_CODE)
#> Joining, by = "ISO3_CODE"

shapeend$value <- as.factor(shapeend$value)


DEU <- shape %>% filter(ISO3_CODE=="DEU")


files <- str_c("./ta_anima/D", str_pad(seq_len(nrow(evo))
  , 3, "left", "0"), ".png")


dates <- as.character(evo$date)

 
for (i in seq_len(nrow(evo))){
datloop <- dates[i]
ggplot(shapeend %>% filter(date ==datloop)) +
  geom_sf(data=bck, fill="lightblue", alpha=0.4) +
  geom_sf(aes(fill=value), show.legend = FALSE, size=0.01) +
  geom_sf(data=DEU, fill="blue", size = 0.01) +
  scale_fill_manual(values = c("#00FF00", "red", "chocolate", "orange", "yellow")) +
  theme_void() +
  theme(plot.background = element_rect(fill="white", color=NA)) +
  labs(
    title = "Corona Atlas",
    subtitle = datloop,
    caption = "Data: Robert Koch Institut",
    fill = ""
  )

ggsave(files[i], width = 1000, height = 700, dpi=300, units = "px")
}

library(gifski)


gifski(files, "tmx_covid.gif", width = 1000, height = 700, loop = FALSE, delay = 0.5)
#> [1] "C:\\Users\\diego\\AppData\\Local\\Temp\\RtmpiI3gt8\\reprex-4e034ac1e65-vivid-eider\\tmx_covid.gif"
```

<sup>Created on 2022-03-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

</details>


![tmx_covid](https://user-images.githubusercontent.com/25656809/156915718-71325588-7447-4a1a-bfdd-41523039c312.gif)

**Comment by rodrihgh** [comment]
I have just added the actual data in
[dev/timelapse/risk_date_countries.csv](https://github.com/dieghernan/RKI-Corona-Atlas/blob/dev/timelapse/risk_date_countries.csv).

Here I have included the risk levels **3** (Risk area) and risk level code **4** (Partial risk area, i.e., which we used, i.e.,
countries which had some regions under moderate risk and some with no risk). These were valid from Apr21 to Aug21. After that, the category "risk area" disappeared and the RKI used only"high-risk area" and "virus variant area".

**Comment by rodrihgh** [comment]
Very nice! I would suggest swapping the colors for "High risk area" and "Variant of concern", as we also ended up doing in the site:

![og-corona](https://raw.githubusercontent.com/dieghernan/RKI-Corona-Atlas/dd94b4c7d02503c5a6a70906d3c58542b1cf57c2/assets/img/og_corona_atlas.png)

**Comment by dieghernan** [comment]
Would do, also I would add Antarctica even though we don't have data (the world map is just incomplete without it, hurt my eyes)

**Comment by rodrihgh** [comment]
Another action point to me: Retrieve older versions of the RKI site by scraping together with a wayback machine.

See for instance [sangaline/scrapy-wayback-machine@22d525d](https://github.com/sangaline/scrapy-wayback-machine)

**Comment by dieghernan** [comment]
Got this so far. 

@rodrihgh if we set a method to update https://github.com/dieghernan/RKI-Corona-Atlas/blob/dev/timelapse/risk_date_countries.csv and we deploy it to master branch, the gif can be created automatically using the gh-action

![covid_timelapse](https://user-images.githubusercontent.com/25656809/157203045-f7d69b99-3c5c-430a-95f5-672e86fcbe62.gif)

**Comment by dieghernan** [comment]
Note that #19 updated the gh-actions, in case you need also to do any modification. It could be a good idea to merge/rebase your branch

**Comment by dieghernan** [comment]
It is set now on `gif` branch, check it

![timelapse](https://raw.githubusercontent.com/dieghernan/RKI-Corona-Atlas/gif/assets/img/corona_atlas_timelapse.gif)
