### ISSUE TITLE
Automatic Python scraping

### ISSUE THREAD

**Issue by rodrihgh** [dieghernan/RKI-Corona-Atlas#4]
Opening this issue as a (self-)reminder.

I have sketched this flowchart as a discussion starter:

![corona-flowchart](https://user-images.githubusercontent.com/4037727/116111028-888af980-a6b6-11eb-8530-94d9590cd6f6.png)

It does not look very complex, GitHub already has examples running Python: https://github.com/actions/starter-workflows/blob/ffb4bccd2d52e308ec66fa63f218d93db6dd94a1/ci/python-app.yml

And there are other [promising examples](https://canovasjm.netlify.app/2020/11/29/github-actions-run-a-python-script-on-schedule-and-commit-changes/) out there.

**Comment by dieghernan** [comment]
Note that we can run all together in the same GitHub Action, i.e. we can integrate the scrapper in the action that we already have.

Also we can adapt the trigger (now it is in every commit/PR, but we can schedule it via cron or set a manual trigger.

**Comment by dieghernan** [comment]
I have created an integrated action with the scraper and the map creation altogether, I suggest working on this direction adding your own improvements on `dev` branch.

https://github.com/dieghernan/RKI-Corona-Atlas/blob/master/.github/workflows/corona-atlas.yml

**Comment by rodrihgh** [comment]
I have finished the action integration, the next running time should be 19h CET.

Please note `on.push.paths` and the like:
https://github.com/dieghernan/RKI-Corona-Atlas/blob/09ef69d9d79797bac9d986a6c179ba7135a98eb9/.github/workflows/corona-atlas.yml#L3-L19

If I understood it correctly, map pages are built from the database and the sources in `_R` so I made that step conditional to avoid periodic unnecessary rebuilds and commits. Review it and change it if needed, please.
