### ISSUE TITLE
R plugins not found

### ISSUE THREAD

**Issue by rodrihgh** [dieghernan/RKI-Corona-Atlas#5]
R elements are not loading in many browsers. I have checked Firefox's console output and it looks like R plugins cannot be found:

[console-export-2021-4-29_10-51-51.txt](https://github.com/dieghernan/RKI-Corona-Atlas/files/6397370/console-export-2021-4-29_10-51-51.txt)

**German hands up:**
  - _Die Ressource von "file.js" wurde wegen eines MIME-Typ-Konfliktes ("text/plain") blockiert_: The resource von "file.js" has been blocked due to a MIME-type conflict ("test/plain")
  - _Laden fehlgeschlagen_: Loading failed

**Comment by dieghernan** [comment]
Can you please recheck? I think now is fixed (tested on Chrome, Firefox, Edge and mobile iOS: Chrome and Safari)

**Comment by dieghernan** [comment]
I am trying something else... let me know if is fixed and if not I can roll back to the previous solution
