### ISSUE TITLE
Turkish page

### ISSUE THREAD

**Issue by rodrihgh** [dieghernan/RKI-Corona-Atlas#8]
Hi @egekorkan !

You only need to modify three files in the [**dev branch**](https://github.com/dieghernan/RKI-Corona-Atlas/tree/dev):

- [assets/data/risk_level_code.csv](https://github.com/dieghernan/RKI-Corona-Atlas/blob/dev/assets/data/risk_level_code.csv) - Translate the risk levels for the column **risk_level_tr**
- [assets/data/idioms.csv](https://github.com/dieghernan/RKI-Corona-Atlas/blob/dev/assets/data/idioms.csv#L7) - Translate the row **tr** with small phrases used to specify dates, table headers, the list of subregions included/excluded in the risk level, etc.
- [_R/index_tr.Rmd](https://github.com/dieghernan/RKI-Corona-Atlas/blob/dev/_R/index_tr.Rmd) - The main text. Think of it as a Markdown document with some small parts of R code.

I have used the English text as the layout but you can go to https://corona-atlas.de/ and check the German or French version as well to get inspiration.

Once you are done I will integrate the Turkish page in the website and add you to the
[Collaborator section](https://corona-atlas.de/about#collaborators). For that you can send me as many links
as you like (LinkedIn, GitHub, your personal website, etc.)

Teşekkürler! 😄

**Comment by dieghernan** [comment]
Hi @egekorkan, I have just invited you as collaborator of the repo

**Comment by egekorkan** [comment]
Thanks @rodrihgh and @dieghernan . I am working on a PR now :) You can simply use my GitHub username for collaborator section once the PR is merged.

**Comment by dieghernan** [comment]
@rodrihgh could you please add @egekorkan as a contributor on the web?

**Comment by rodrihgh** [comment]
I have added a couple of missing translations, @egekorkan could you check? I have already added you to the collaborators, by the way.

**Comment by egekorkan** [comment]
@rodrihgh I must have missed them :D I have checked https://github.com/dieghernan/RKI-Corona-Atlas/commit/f7e448e189f2192300d8fa446f6256e1202cc0d8 and they look good. Good job :smile:
